sudo: false

dist: xenial

branches:
  only:
    - master

services:
  - docker

# Build API reference
script:
  - docker pull alpine:3.10
  - docker run -v $PWD:/home alpine:3.10 /bin/sh -c "cd /home/docs && apk update && apk add doxygen && doxygen Doxyfile;"

# Deploy API reference
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
