/*
 * Milestone:
 * This file was generated by GStreamer's make_template script.
 * This element takes video frame input and metadata input and joins them into one output.
 * It has two sinks:
 * - Video sink: Video input as raw frames in the gstbuffers.
 * - Metadata sink: Empty gstbuffers with xprotectmeta attached.
 * The element outputs the video buffers with the xprotectmeta attached.
 *
 * GStreamer
 * Copyright (C) 2005 Thomas Vander Stichele <thomas@apestaart.org>
 * Copyright (C) 2005 Ronald S. Bultje <rbultje@ronald.bitfreak.net>
 * Copyright (C) 2019  <<user@hostname.org>>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Alternatively, the contents of this file may be used under the
 * GNU Lesser General Public License Version 2.1 (the "LGPL"), in
 * which case the following provisions apply instead of the ones
 * mentioned above:
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

 /**
  * SECTION:element-toxprotectconverter
  *
  * The element xprotectjoin will join a gstbuffer containing raw video data with
  * an empty gstbuffer with an xprotectmeta attached.
  *
  * <refsect2>
  * <title>Example launch line</title>
  * |[
  * gst-launch -v -m fakesrc ! xprotectjoin ! fakesink
  * ]|
  * </refsect2>
  */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <stdio.h>
#include <time.h>
#include <gst/gst.h>
#include "../../Meta/gstvpsxprotectmeta/gstvpsxprotectmeta.h"
#include "../../VpsUtilities/GenericByteData/GenericByteData.h"
#include "gstvpsxprotectjoin.h"
#include "gstvpsxprotect.h"

  /* Filter signals and args */
enum
{
  /* FILL ME */
  LAST_SIGNAL
};

enum
{
  PROP_0
};

/* the capabilities of the inputs and outputs.
 *
 * describe the real formats here.
 */
static GstStaticPadTemplate sink_video_factory = GST_STATIC_PAD_TEMPLATE("sink_video",
  GST_PAD_SINK,
  GST_PAD_ALWAYS,
  GST_STATIC_CAPS("ANY")
);

static GstStaticPadTemplate sink_metadata_factory = GST_STATIC_PAD_TEMPLATE("sink_metadata",
  GST_PAD_SINK,
  GST_PAD_ALWAYS,
  GST_STATIC_CAPS("ANY")
);

static GstStaticPadTemplate src_factory = GST_STATIC_PAD_TEMPLATE("src",
  GST_PAD_SRC,
  GST_PAD_ALWAYS,
  GST_STATIC_CAPS("ANY")
);

#define gst_toxprotectconverter_parent_class parent_class
G_DEFINE_TYPE(GstXprotectJoin, gst_xprotectjoin, GST_TYPE_BIN);

static gboolean gst_xprotectjoin_sink_event(GstPad * pad, GstObject * parent, GstEvent * event);
static gboolean gst_xprotectjoin_sink_meta_event(GstPad * pad, GstObject * parent, GstEvent * event);
static GstFlowReturn gst_xprotectjoin_chain(GstPad * pad, GstObject * parent, GstBuffer * buf);
static GstFlowReturn gst_xprotectjoin_metadata_chain(GstPad * pad, GstObject * parent, GstBuffer * buf);

/* GObject vmethod implementations */

/* initialize the toxprotectconverter's class */
static void
gst_xprotectjoin_class_init(GstXprotectJoinClass * klass)
{
  GST_DEBUG_CATEGORY_INIT(gst_xprotect_debug, "xprotect",
    0, "Template xprotectjoin");
  GObjectClass *gobject_class;
  GstElementClass *gstelement_class;

  gobject_class = (GObjectClass *)klass;
  gstelement_class = (GstElementClass *)klass;

  gst_element_class_set_details_simple(gstelement_class,
    "xprotectjoin",
    "VPS/test",
    "xprotectjoin will join a gstbuffer containing raw video data with an empty gstbuffer with an xprotectmeta attached.",
    "developer.milestonesys.com");

  gst_element_class_add_pad_template(gstelement_class,
    gst_static_pad_template_get(&src_factory));
  gst_element_class_add_pad_template(gstelement_class,
    gst_static_pad_template_get(&sink_video_factory));
  gst_element_class_add_pad_template(gstelement_class,
    gst_static_pad_template_get(&sink_metadata_factory));
}

/* initialize the new element
 * instantiate pads and add them to element
 * set pad calback functions
 * initialize instance structure
 */
static void gst_xprotectjoin_init(GstXprotectJoin * filter)
{
  if (filter == NULL)
  {
    GST_ERROR("Filter parameter was NULL.");
    return;
  }
  filter->sinkpad_video = gst_pad_new_from_static_template(&sink_video_factory, "sink_video");
  gst_pad_set_event_function(filter->sinkpad_video,
    GST_DEBUG_FUNCPTR(gst_xprotectjoin_sink_event));
  gst_pad_set_chain_function(filter->sinkpad_video,
    GST_DEBUG_FUNCPTR(gst_xprotectjoin_chain));
  GST_PAD_SET_PROXY_CAPS(filter->sinkpad_video);
  gst_element_add_pad(GST_ELEMENT(filter), filter->sinkpad_video);

  filter->sinkpad_metadata = gst_pad_new_from_static_template(&sink_metadata_factory, "sink_metadata");
  gst_pad_set_event_function(filter->sinkpad_metadata,
    GST_DEBUG_FUNCPTR(gst_xprotectjoin_sink_meta_event));
  gst_pad_set_chain_function(filter->sinkpad_metadata,
    GST_DEBUG_FUNCPTR(gst_xprotectjoin_metadata_chain));
  GST_PAD_SET_PROXY_CAPS(filter->sinkpad_metadata);
  gst_element_add_pad(GST_ELEMENT(filter), filter->sinkpad_metadata);

  filter->srcpad = gst_pad_new_from_static_template(&src_factory, "src");
  GST_PAD_SET_PROXY_CAPS(filter->srcpad);
  gst_element_add_pad(GST_ELEMENT(filter), filter->srcpad);

  filter->metadata_queue = g_queue_new();
}

/* GstElement vmethod implementations */

/* this function handles sink events */
static gboolean
gst_xprotectjoin_sink_event(GstPad * pad, GstObject * parent, GstEvent * event)
{
  GstXprotectJoin *filter;
  gboolean ret;

  filter = GST_XPROTECTJOIN(parent);

  GST_LOG_OBJECT(filter, "Received %s event: %" GST_PTR_FORMAT,
    GST_EVENT_TYPE_NAME(event), event);

  switch (GST_EVENT_TYPE(event)) {
  case GST_EVENT_CAPS:
  {
    GstCaps * caps;

    gst_event_parse_caps(event, &caps);

    /* and forward */
    ret = gst_pad_event_default(pad, parent, event);
    break;
  }
  default:
    ret = gst_pad_event_default(pad, parent, event);
    break;
  }
  return ret;
}

static gboolean
gst_xprotectjoin_sink_meta_event(GstPad * pad, GstObject * parent, GstEvent * event)
{
  GstXprotectJoin *filter;
  gboolean ret;

  filter = GST_XPROTECTJOIN(parent);

  GST_LOG_OBJECT(filter, "Received %s event: %" GST_PTR_FORMAT,
    GST_EVENT_TYPE_NAME(event), event);

  switch (GST_EVENT_TYPE(event)) {
  case GST_EVENT_CAPS:
  {
    GstCaps * caps;

    gst_event_parse_caps(event, &caps);
    ret = true;
    break;
  }
  case GST_EVENT_SEGMENT:
  {
    const GstSegment * segment;

    gst_event_parse_segment(event, &segment);
    ret = true;
    break;
  }
  default:
    ret = gst_pad_event_default(pad, parent, event);
    break;
  }
  return ret;
}

/*
 * Chain function for video frames.
 * this function copies the incoming video data to an output buffer and attaches
 * the GstXprotectMeta to that buffer containing information about the video data.
 */
static GstFlowReturn gst_xprotectjoin_chain(GstPad * pad, GstObject * parent, GstBuffer * buf)
{
  GstXprotectJoin *filter;

  filter = GST_XPROTECTJOIN(parent);
  GstXprotectMeta * meta_to_add = (GstXprotectMeta *)(g_queue_pop_head(filter->metadata_queue));
  if (meta_to_add == NULL) {
    return gst_pad_push(filter->srcpad, buf);
  }

  GstMapInfo info;
  gst_buffer_map(buf, &info, GST_MAP_READ);

  GstBuffer * outputBuffer = gst_buffer_new();
  GstMemory * mem = gst_allocator_alloc(NULL, info.size, NULL);
  gst_buffer_append_memory(outputBuffer, mem);
  GstMapInfo info2;
  gst_buffer_map(outputBuffer, &info2, GST_MAP_WRITE);

  gst_buffer_add_xprotect_meta(outputBuffer, meta_to_add->sequence_number, meta_to_add->sync_timestamp, meta_to_add->timestamp);
  delete meta_to_add;
  memcpy(info2.data, info.data, info.size);

  gst_buffer_unmap(outputBuffer, &info2);
  gst_buffer_unmap(buf, &info);
  gst_buffer_unref(buf);

  return gst_pad_push(filter->srcpad, outputBuffer);
}

/*
 * Chain function for GstXprotectMeta.
 * This function puts the GstXprotectMeta into a queue that will be popped from the video frame chain function.
 */
static GstFlowReturn gst_xprotectjoin_metadata_chain(GstPad * pad, GstObject * parent, GstBuffer * buf)
{
  GstXprotectJoin *filter;

  filter = GST_XPROTECTJOIN(parent);
  guint64 timestamp, sync_timestamp;
  guint32 sequence_number;

  GstXprotectMeta * meta = gst_buffer_get_xprotect_meta(buf);
  if (meta != NULL)
  {
    sequence_number = meta->sequence_number;
    sync_timestamp = meta->sync_timestamp;
    timestamp = meta->timestamp;
    GST_TRACE("META seq no: %d\n", sequence_number);

    GstXprotectMeta* localMeta = new GstXprotectMeta;
    localMeta->sequence_number = sequence_number;
    localMeta->sync_timestamp = sync_timestamp;
    localMeta->timestamp = timestamp;

    g_queue_push_tail(filter->metadata_queue, localMeta);
  }
  gst_buffer_unref(buf);

  return GST_FLOW_OK;
}
