/*
 * Milestone:
 * This file was generated by GStreamer's make_template script.
 * It passes H.264 encoded video coming from an XProtect system into OpenVINO face detection,
 * strips the video and returns ONVIF bounding boxes to XProtect VMS
 * Please note that this code has hardcoded paths to where the OpenVINO is installed
 *
 * GStreamer
 * Copyright (C) 2005 Thomas Vander Stichele <thomas@apestaart.org>
 * Copyright (C) 2005 Ronald S. Bultje <rbultje@ronald.bitfreak.net>
 * Copyright (C) 2019  <<user@hostname.org>>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Alternatively, the contents of this file may be used under the
 * GNU Lesser General Public License Version 2.1 (the "LGPL"), in
 * which case the following provisions apply instead of the ones
 * mentioned above:
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/**
 * SECTION:element-vpsopenvinofaces
 *
 * Passes H.264 encoded video coming from an XProtect system into OpenVINO face detection gvadetect
 *
 * <refsect2>
 * <title>Example launch line</title>
 * |[
 * gst-launch -v -m fakesrc ! vpsopenvinofaces ! fakesink
 * ]|
 * </refsect2>
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


#include <gst/gst.h>
#include "gstvpsopenvinofaces.h"

GST_DEBUG_CATEGORY_STATIC (gst_vpsopenvinofaces_debug);
#define GST_CAT_DEFAULT gst_vpsopenvinofaces_debug

/* Filter signals and args */
enum
{
  /* FILL ME */
  LAST_SIGNAL
};

enum
{
  PROP_0
};

/* the capabilities of the inputs and outputs.
 *
 * describe the real formats here.
 */
static GstStaticPadTemplate sink_factory = GST_STATIC_PAD_TEMPLATE ("sink",
    GST_PAD_SINK,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS ("ANY")
    );

static GstStaticPadTemplate src_factory = GST_STATIC_PAD_TEMPLATE ("src",
    GST_PAD_SRC,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS ("ANY")
    );

#define gst_vpsopenvinofaces_parent_class parent_class
G_DEFINE_TYPE (GstVpsOpenVinoFaces, gst_vpsopenvinofaces, GST_TYPE_BIN);

static gboolean gst_vpsopenvinofaces_sink_event (GstPad * pad, GstObject * parent, GstEvent * event);

/* GObject vmethod implementations */

/* initialize the vpsopenvinofaces's class */
static void gst_vpsopenvinofaces_class_init (GstVpsOpenVinoFacesClass * klass)
{
  GObjectClass *gobject_class;
  GstElementClass *gstelement_class;

  gobject_class = (GObjectClass *) klass;
  gstelement_class = (GstElementClass *) klass;

  gst_element_class_set_details_simple(gstelement_class,
    "vpsopenvinofaces",
    "VPS/test",
    "Passes H.264 encoded video coming from an XProtect system into OpenVINO face detection gvadetect",
    "developer.milestonesys.com");

  gst_element_class_add_pad_template (gstelement_class,
      gst_static_pad_template_get (&src_factory));
  gst_element_class_add_pad_template (gstelement_class,
      gst_static_pad_template_get (&sink_factory));
}

/* initialize the new element
 * instantiate pads and add them to element
 * set pad calback functions
 * initialize instance structure
 */
static void gst_vpsopenvinofaces_init (GstVpsOpenVinoFaces * filter)
{
  if (filter != NULL)
  {    
	  // Create the xprotect element to remove generic byte data headers from the video frames
    filter->header_remover = gst_element_factory_make("fromxprotectconverter", "header_remover");
    if (!filter->header_remover)
    {
      GST_ERROR("Failed to create header_remover element.");
    }

	  // Create the video queue element
    filter->queue_video = gst_element_factory_make("queue", "queue_video");
    if (!filter->queue_video)
    {
      GST_ERROR("Failed to create queue_video element.");
    }

	  // Create the metadata queue element
    filter->queue_metadata = gst_element_factory_make("queue", "queue_metadata");
    if (!filter->queue_metadata)
    {
      GST_ERROR("Failed to create queue_metadata element.");
    }

    // Create the decoder element
    filter->decoder = gst_element_factory_make("decodebin", "decoder");
    if (!filter->decoder)
    {
      GST_ERROR("Failed to create decoder element.");
    }

    // Create the videoconvert element
    filter->videoconvert = gst_element_factory_make("videoconvert", "videoconvert");
    if (!filter->videoconvert)
    {
      GST_ERROR("Failed to create videoconvert element.");
    }

    filter->gvadetect = gst_element_factory_make("gvadetect", "gvadetect");
    if (!filter->gvadetect)
    {
      GST_ERROR("Failed to create gvadetect element.");
    }
	  g_object_set(filter->gvadetect,
	    "model", "/opt/intel/openvino_2019.3.376/deployment_tools/open_model_zoo/tools/downloader/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml",
	    "device", "CPU",
	    "pre_proc", "opencv",
	    NULL);

	  // Create the after-gvadetect queue element
    filter->queue_gvadetect = gst_element_factory_make("queue", "queue_gvadetect");
    if (!filter->queue_gvadetect)
    {
      GST_ERROR("Failed to create queue_gvadetect element.");
    }

    filter->age_gender = gst_element_factory_make("gvaclassify", "age_gender");
    if (!filter->age_gender)
    {
      GST_ERROR("Failed to create age_gender element.");
    }
	  g_object_set(filter->age_gender,
	    "model", "/opt/intel/openvino_2019.3.376/deployment_tools/open_model_zoo/tools/downloader/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml",
	    "model-proc", "/home/openvino/gst-video-analytics-master/gvam/scripts/../samples/model_proc/age-gender-recognition-retail-0013.json",
	    "device", "CPU",
	    "pre_proc", "opencv",
	    NULL);
    
    filter->fakesink = gst_element_factory_make("fakesink", "fakesink");
    if (!filter->fakesink)
    {
      GST_ERROR("Failed to create fakesink element.");
    }

    filter->meta_onvif = gst_element_factory_make("vpsmetafromroi", "meta_onvif");
    if (!filter->meta_onvif)
    {
      GST_ERROR("Failed to create meta_onvif element.");
    }
	        
    // Add them to the bin
    gst_bin_add((GstBin*)filter, filter->header_remover);
    gst_bin_add((GstBin*)filter, filter->decoder);
    gst_bin_add((GstBin*)filter, filter->videoconvert);	
    gst_bin_add((GstBin*)filter, filter->gvadetect);
    gst_bin_add((GstBin*)filter, filter->fakesink);
    gst_bin_add((GstBin*)filter, filter->queue_video);
    gst_bin_add((GstBin*)filter, filter->queue_metadata);
    gst_bin_add((GstBin*)filter, filter->meta_onvif);	
    gst_bin_add((GstBin*)filter, filter->age_gender);	
    gst_bin_add((GstBin*)filter, filter->queue_gvadetect);	
		
    // Eliminate the generic byte date headers by passing them to fakesink via queue_metadata
    GstPad *src_pad = gst_element_get_static_pad(filter->header_remover, "src_metadata");
    GstPad *sink_pad = gst_element_get_static_pad(filter->queue_metadata, "sink");
	  if (!src_pad) g_print ("srcpad is NULL\n");
	  if (!sink_pad) g_print ("sinkpad is NULL\n");
    GstPadLinkReturn ret = gst_pad_link(src_pad, sink_pad);
    if (GST_PAD_LINK_FAILED(ret)) 
	  {
      GST_ERROR("header_remover:src_metadata and queue_metadata could not be linked.\n");
    }
    gst_object_unref(src_pad);
    gst_object_unref(sink_pad);

	  // Connect the output from the queue_metadata to the input of fakesink
    if (gst_element_link(filter->queue_metadata, filter->fakesink) != (gboolean)TRUE)
    {
      GST_ERROR("queue_metadata and fakesink could not be linked.\n");
    }

	  // Connect the output video source from the header-remover to the input sink of the video queue
    src_pad = gst_element_get_static_pad(filter->header_remover, "src_video");
    sink_pad = gst_element_get_static_pad(filter->queue_video, "sink");
    ret = gst_pad_link(src_pad, sink_pad);
    if (GST_PAD_LINK_FAILED(ret)) 
	  {
      GST_ERROR("header_remover:src_video and queue_video:sink could not be linked.\n");
    }
    gst_object_unref(src_pad);
    gst_object_unref(sink_pad);
	
	  // Connect the output from the queue_video to the input of decoder
    if (gst_element_link(filter->queue_video, filter->decoder) != (gboolean)TRUE)
    {
      GST_ERROR("queue_video and videoconvert could not be linked.\n");
    }
	
	  // Video decoder and videoconvert will be connected later in the pad_added_handler callback
	  g_signal_connect(filter->decoder, "pad-added", G_CALLBACK(pad_added_handler), filter->videoconvert);

	  // Connect the output from the videoconvert to the input of the face detector
    if (gst_element_link(filter->videoconvert, filter->gvadetect) != (gboolean)TRUE)
    {
      GST_ERROR("videoconvert and gvadetect could not be linked.\n");
    }

	  // Connect the output from the face detection to the gvadetect queue
    if (gst_element_link(filter->gvadetect, filter->queue_gvadetect) != (gboolean)TRUE)
    {
      GST_ERROR("gvadetect and queue_gvadetect could not be linked.\n");
    }

	  // Connect the output from the queue_gvadetect to the input of the age_gender detection
    if (gst_element_link(filter->queue_gvadetect, filter->age_gender) != (gboolean)TRUE)
    {
      GST_ERROR("queue_gvadetect and age_gender could not be linked.\n");
    }

	  // Connect the output from the age_gender to the input of the vpsmetafromroi which creates the ONVIF metadata and strips the video
    if (gst_element_link(filter->age_gender, filter->meta_onvif) != (gboolean)TRUE)
    {
      GST_ERROR("age_gender and meta_onvif could not be linked.\n");
    }
	
	  // Expose the header remover sink to the vps2gstreamer pipeline, so we receive video data in this pipeline
	  GstPad *gstpadsink = gst_element_get_static_pad(filter->header_remover, "sink");
    if (!gstpadsink)
    {
      GST_ERROR("Could not find '%s' in '%s'", "sink", "filter->header_remover");
    }
	  gst_element_add_pad((GstElement *)filter, gst_ghost_pad_new("sink", gstpadsink));
    gst_object_unref(gstpadsink);

	  // Expose the vpsmetafromroi source with ONVIF metadata to the vps2gstreamer pipeline
    // The vps2gstreamer queues up data for the web server to go collect from, so no GStreamer queue element is needed in between
    GstPad *gstpadsrc = gst_element_get_static_pad(filter->meta_onvif, "src");
    if (!gstpadsrc)
    {
      GST_ERROR("Could not find '%s' in '%s'", "src", "filter->meta_onvif");
    }
    gst_element_add_pad((GstElement *)filter, gst_ghost_pad_new("src", gstpadsrc));
    gst_object_unref(gstpadsrc);
  }
}

/* GstElement vmethod implementations */

/* this function handles sink events */
static gboolean gst_vpsopenvinofaces_sink_event (GstPad * pad, GstObject * parent, GstEvent * event)
{
  GstVpsOpenVinoFaces *filter;
  gboolean ret;

  filter = GST_VPSOPENVINOFACES (parent);

  GST_LOG_OBJECT (filter, "Received %s event: %" GST_PTR_FORMAT, GST_EVENT_TYPE_NAME (event), event);

  switch (GST_EVENT_TYPE (event)) 
  {
    case GST_EVENT_CAPS:
    {
      GstCaps * caps;

      gst_event_parse_caps (event, &caps);
      /* do something with the caps */

      /* and forward */
      ret = gst_pad_event_default (pad, parent, event);
      break;
    }
    default:
      ret = gst_pad_event_default (pad, parent, event);
      break;
  }
  return ret;
}

/* entry point to initialize the plug-in
 * initialize the plug-in itself
 * register the element factories and other features
 */
static gboolean vpsopenvinofaces_init (GstPlugin * vpsopenvinofaces)
{
  /* debug category for filtering log messages
   */
  GST_DEBUG_CATEGORY_INIT (gst_vpsopenvinofaces_debug, "vpsopenvinofaces",
      0, "Passes H.264 encoded video coming from an XProtect system into OpenVINO face detection gvadetect");

  return gst_element_register (vpsopenvinofaces, "vpsopenvinofaces", GST_RANK_NONE, GST_TYPE_VPSOPENVINOFACES);
}

static void pad_added_handler(GstElement *src, GstPad *new_pad, GstElement *other) 
{
  gchar * otherName = gst_pad_get_name(new_pad);
  GST_INFO("New pad %s added for %s", otherName, gst_element_get_name(other));
  g_free(otherName);
  
  GstPad *sink_pad = gst_element_get_static_pad(other, "sink");
  if (!sink_pad) 
  {
    GST_ERROR("Pad named sink could not be found in %s\n", gst_element_get_name(other));
  }

  GstPadLinkReturn ret = gst_pad_link(new_pad, sink_pad);
  if (GST_PAD_LINK_FAILED(ret)) 
  {
    GST_ERROR("Decoder and %s could not be linked.\n", gst_element_get_name(other));
  }
  gst_object_unref(sink_pad);
}

/* PACKAGE: this is usually set by autotools depending on some _INIT macro
 * in configure.ac and then written into and defined in config.h, but we can
 * just set it ourselves here in case someone doesn't use autotools to
 * compile this code. GST_PLUGIN_DEFINE needs PACKAGE to be defined.
 */
#ifndef PACKAGE
#define PACKAGE "gst-vps-test"
#endif

#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION "1.0"
#endif

#ifndef GST_PACKAGE_NAME
#define GST_PACKAGE_NAME "VPS Gstreamer test plugin package"
#endif

#ifndef GST_PACKAGE_ORIGIN
#define GST_PACKAGE_ORIGIN "Milestone Systems"
#endif

#ifndef GST_LICENSE
#define GST_LICENSE "LGPL"
#endif


/* gstreamer looks for this structure to register vpsopenvinofaces
 */
GST_PLUGIN_DEFINE (
    GST_VERSION_MAJOR,
    GST_VERSION_MINOR,
    vpsopenvinofaces,
    "Passes H.264 encoded video coming from an XProtect system into OpenVINO face detection gvadetect. Returns ONVIF bounding boxes.",
    vpsopenvinofaces_init,
    PACKAGE_VERSION,
    GST_LICENSE,
    GST_PACKAGE_NAME,
    GST_PACKAGE_ORIGIN
)
